# Generated by Django 5.1.1 on 2024-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0002_alter_favorito_aviso_alter_favorito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='slug',
            field=models.SlugField(default='asd', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
