# Generated by Django 5.1.1 on 2024-09-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0003_aviso_slug'),
        ('Propiedades', '0003_alter_propiedad_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='propiedad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aviso', to='Propiedades.propiedad'),
        ),
    ]
