# Generated by Django 5.1.1 on 2024-10-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0005_alerta_avisoalerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo_operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Avisos.tipooperacion'),
        ),
    ]
