# Generated by Django 5.1.1 on 2024-10-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0006_alter_alerta_tipo_operacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='propiedad_banos_max',
            new_name='propiedad_baños_max',
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='propiedad_banos_min',
            new_name='propiedad_baños_min',
        ),
    ]
