# Generated by Django 5.1.1 on 2024-10-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0007_rename_propiedad_banos_max_alerta_propiedad_baños_max_and_more'),
        ('Propiedades', '0006_alter_propiedad_area_construida_and_more'),
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_area_construida_max',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_area_construida_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_area_total_max',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_area_total_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_ascensores_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_ascensores_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_baños_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_baños_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_estacionamientos_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_estacionamientos_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_habitaciones_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_habitaciones_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_mantenimiento_max',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_mantenimiento_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_pisos_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_pisos_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_precio_dolares_max',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_precio_dolares_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_subtipo_propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Propiedades.subtipopropiedad'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_tipo_antiguedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Propiedades.tipoantiguedad'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_tipo_propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Propiedades.tipopropiedad'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_ubicacion_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ubicacion.distrito'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_ubicacion_distrito_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ubicacion.provincia'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='propiedad_ubicacion_distrito_provincia_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ubicacion.departamento'),
        ),
    ]
