# Generated by Django 5.1.1 on 2024-09-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
