# Generated by Django 5.1.1 on 2024-10-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='descripcion',
        ),
    ]
