# Generated by Django 5.1.1 on 2024-10-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicacion', '0002_remove_departamento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
