# Generated by Django 5.1.1 on 2024-09-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0003_alter_propiedad_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpropiedad',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='planopropiedad',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
