# Generated by Django 5.1.1 on 2024-10-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0004_imagenpropiedad_titulo_planopropiedad_titulo'),
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UbicaciónPropiedad',
            new_name='UbicacionPropiedad',
        ),
    ]
